package clasesH;
// Generated 21-feb-2020 17:01:37 by Hibernate Tools 5.4.7.Final

/**
 * Carman generated by hbm2java
 */
public class Carman implements java.io.Serializable {

	private CarmanId id;
	private Cartas cartas;
	private Mano mano;
	private boolean usada;

	public Carman() {
	}

	public Carman(CarmanId id, Cartas cartas, Mano mano, boolean usada) {
		this.id = id;
		this.cartas = cartas;
		this.mano = mano;
		this.usada = usada;
	}

	public CarmanId getId() {
		return this.id;
	}

	public void setId(CarmanId id) {
		this.id = id;
	}

	public Cartas getCartas() {
		return this.cartas;
	}

	public void setCartas(Cartas cartas) {
		this.cartas = cartas;
	}

	public Mano getMano() {
		return this.mano;
	}

	public void setMano(Mano mano) {
		this.mano = mano;
	}

	public boolean isUsada() {
		return this.usada;
	}

	public void setUsada(boolean usada) {
		this.usada = usada;
	}

}
