package clasesH;
// Generated 21-feb-2020 17:01:37 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Mano generated by hbm2java
 */
public class Mano implements java.io.Serializable {

	private Integer idMano;
	private Partida partida;
	private boolean player;
	private Set carmans = new HashSet(0);

	public Mano() {
	}

	public Mano(Partida partida, boolean player) {
		this.partida = partida;
		this.player = player;
	}

	public Mano(Partida partida, boolean player, Set carmans) {
		this.partida = partida;
		this.player = player;
		this.carmans = carmans;
	}

	public Integer getIdMano() {
		return this.idMano;
	}

	public void setIdMano(Integer idMano) {
		this.idMano = idMano;
	}

	public Partida getPartida() {
		return this.partida;
	}

	public void setPartida(Partida partida) {
		this.partida = partida;
	}

	public boolean isPlayer() {
		return this.player;
	}

	public void setPlayer(boolean player) {
		this.player = player;
	}

	public Set getCarmans() {
		return this.carmans;
	}

	public void setCarmans(Set carmans) {
		this.carmans = carmans;
	}

}
