package clasesH;
// Generated 21-feb-2020 17:01:37 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Partida generated by hbm2java
 */
public class Partida implements java.io.Serializable {

	private Integer idGame;
	private Jugadores jugadores;
	private boolean terminado;
	private Set manos = new HashSet(0);

	public Partida() {
	}

	public Partida(Jugadores jugadores, boolean terminado) {
		this.jugadores = jugadores;
		this.terminado = terminado;
	}

	public Partida(Jugadores jugadores, boolean terminado, Set manos) {
		this.jugadores = jugadores;
		this.terminado = terminado;
		this.manos = manos;
	}

	public Integer getIdGame() {
		return this.idGame;
	}

	public void setIdGame(Integer idGame) {
		this.idGame = idGame;
	}

	public Jugadores getJugadores() {
		return this.jugadores;
	}

	public void setJugadores(Jugadores jugadores) {
		this.jugadores = jugadores;
	}

	public boolean isTerminado() {
		return this.terminado;
	}

	public void setTerminado(boolean terminado) {
		this.terminado = terminado;
	}

	public Set getManos() {
		return this.manos;
	}

	public void setManos(Set manos) {
		this.manos = manos;
	}

}
